=== addon-ai/back-ms-users/schemas/back-ms-users-location/CreateLocationRequest.json
{
  "type": "object",
  "properties": {
    "userId": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "id"
    },
    "countryId": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "id"
    },
    "regionId": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "id"
    },
    "cityId": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "id"
    },
    "neighborhoodId": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "id"
    },
    "address": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "address"
    },
    "postalCode": {
      "type": "string",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "postalCode"
    },
    "latitude": {
      "type": "number",
      "format": "double",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "latitude"
    },
    "longitude": {
      "type": "number",
      "format": "double",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "longitude"
    },
    "locationType": {
      "$ref": "#/components/schemas/LocationType",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "locationType"
    }
  },
  "required": [
    "address",
    "cityId",
    "countryId",
    "locationType",
    "regionId",
    "userId"
  ],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "CreateLocationRequest"
}

=== addon-ai/back-ms-users/schemas/back-ms-users-location/fake-data/CreateLocationRequest.json
{
  "userId": "5fa3ce5f-111f-4b6f-a0e0-5d84e80067f0",
  "countryId": "1da38a50-e4d9-4fa0-b006-9dd88f459812",
  "regionId": "0c54a89d-2ab5-4d8c-b85a-3f0eec8cda2e",
  "cityId": "b16122db-aff5-457f-ab6b-95b5e26a7739",
  "neighborhoodId": "05c146f6-9bce-4c42-af37-7ebe5d34c987",
  "address": "",
  "longitude": 4525.0,
  "locationType": "HOME"
}
